### ISSUE TITLE
Checking packages crashes

### ISSUE THREAD

**Issue by stdevel** [stdevel/check_pakfire#1]
Checking for outdateds packages is not possible due to a typo in the code:
```
# ./check_pakfire.py -i
Traceback (most recent call last):
  File "./check_pakfire.py", line 195, in <module>
    checkUpdates()
  File "./check_pakfire.py", line 134, in checkUpdates
    if boolCore == True and boolPKgs == False:
NameError: global name 'boolPKgs' is not defined
```

Checking the core update works without any issues:
```
# ./check_pakfire.py 
OK: Core Update '103' for release '2.19' up2date!
```

**Comment by stdevel** [comment]
Fixed in commit 6b5a3eb00dca02c7ed22037e9624cfebc1027854.
